dist: bionic
language: node_js
cache: yarn
node_js:
    - lts/*

install:
    - yarn install

script:
    - yarn dist

deploy:
    skip_cleanup: true
    provider: script
    script: sh bin/deploy.sh $SFTP_USER SFTP_HOST
