os: linux
dist: bionic
language: node_js
cache: yarn
node_js:
    - lts/*
addons:
    ssh_known_hosts: agricontrol.app

install:
    - yarn install

script:
    - yarn dist

deploy:
    cleanup: false
    provider: script
    script: sh bin/deploy.sh $SFTP_USER $SFTP_HOST
